version: '2.1'

x-logging:
  &default-logging
  options:
    max-file: '1'
    compress: 'false'
  driver: local

networks:
  graph_net:
    driver: bridge
    name: graph_net
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
    

volumes:
    postgres_data: {}

services:

######################################################################################
#####################            POSTGRES CONTAINER            #######################
######################################################################################



  postgres:
    image: postgres:13.6
    container_name: postgres
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-graph-node}
      POSTGRES_PASSWORD: ${DB_PASS:-db-password}
      POSTGRES_DB: ${GRAPH_NODE_DB_NAME:-graph-node}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-socket:/var/run/postgresql
    networks:
      - graph_net
    expose:
      - 5432
    logging: *default-logging



