version: '2.1'

x-logging:
  &default-logging
  options:
    max-file: '1'
    compress: 'false'
  driver: local

networks:
  graph_net:
    name: graph_net

volumes:
    postgres_mainnet_agent_data: {}

services:


######################################################################################
#####################    POSTGRES AGENT MAINNET CONTAINER      #######################
######################################################################################



  postgres-mainnet-agent:
    image: postgres:13.6
    container_name: postgres-mainnet-agent
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-graph-node}
      POSTGRES_PASSWORD: ${DB_PASS:-db-password}
      POSTGRES_DB: ${INDEXER_DB_NAME_MAINNET:-indexer-agent-mainnet}
    volumes:
      - postgres_mainnet_agent_data:/var/lib/postgresql/data
    networks:
      - graph_net
    expose:
      - 5432
    logging: *default-logging

