#!/bin/bash
ENV_FILE=".env"

set -a
source <(cat "$ENV_FILE" | sed -e '/^#/d;/^\s*$/d' -e "s/'/'\\\''/g" -e "s/=\(.*\)/='\1'/g")
set +a

IFS=':' read -ra FILES <<< ${COMPOSE_FILE}
for i in "${FILES[@]}"; do [ "$i" != "proxy.yml" ] && SHUTDOWN+="-f $(pwd)/$i "; done

docker-compose ${SHUTDOWN} down ${@} #--remove-orphans